services:
  postgres:
    container_name: db-products
    image: 'postgres:16.1-alpine'
    environment:
      - 'POSTGRES_DB=products'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
